#Cookie获取订阅
#Cookie获取成功后在重写里禁用掉本订阅
#Cookie失效时在重写里启用本订阅

hostname = *.quark.cn

# 夸克获取Cookie
^https:\/\/pan\.quark\.cn url script-request-header https://raw.githubusercontent.com/PublicClassKF/QuantumultX/refs/heads/master/Quark/quark_ck.js
